apache:
  container_name: apache
  build: ./apache
  ports:
    - "80:80"
  volumes:
    - ./http/www:/var/www/html
  links: 
    - mysql

mysql:
  container_name: mysql
  build: ./mysql
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=kermit
   - MYSQL_DATABASE=testing
